#!/bin/sh

# Download all datasets on Socrata.
# Requires curl and jq.
# Datasets are saved to datasets/<id>/rows.csv and the metadata is saved to
# datasets/<id>/metadata.json where <id> is the Socrata dataset four-by-four.

if [ -d datasets ]; then
    echo "datasets directory already exists"
    exit 1
fi

mkdir datasets
cd datasets || exit 1

# Limited to NYC health data for now (~120 datasets).
discovery_api_url='http://api.us.socrata.com/api/catalog/v1?domains=data.cityofnewyork.us&categories=Health&only=datasets&limit=1000'

curl -# "$discovery_api_url" -o catalog.json

jq -c '.results[]' catalog.json |
while IFS= read -r resource
do
    id=$(echo "$resource" | jq -r '.resource.id')
    echo "Downloading dataset $id"
    mkdir "$id"
    echo "$resource" | jq > "$id/metadata.json"
    domain=$(echo "$resource" | jq -r '.metadata.domain')
    download_url="$domain/api/views/$id/rows.csv?accessType=DOWNLOAD"
    curl -# "$download_url" -o "$id/rows.csv"
done
